function cellInfo = Linear_DeltaStates_Bus(varargin) 
% LINEAR_DELTASTATES_BUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Linear_ControlsAction_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'delta_elevator_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_aileron_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_rudder_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_thrust_action_lbs', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Linear_DeltaStates_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'delta_p_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_r_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_phi_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_psi_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_q_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_theta_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_beta_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Linear_States_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'p_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'q_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'r_radsec', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'phi_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'theta_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'psi_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'alpha_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'beta_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Vtot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Vtot_calc', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'H_calc_ft', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'gamma_calc_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'alpha_calc_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Xe_ft', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Ye_ft', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'H_ft', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Nonlinear_ControlsAction_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'delta_elevator_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_aileron_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_rudder_action_rad', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'delta_thrust_action_lbs', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Nonlinear_States_Bus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'x', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'y', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'z', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft'), ''}; ...
{'phi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'theta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'psi', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'u', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'v', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'w', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
{'p', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/sec'), ''}; ...
{'q', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/sec'), ''}; ...
{'r', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad/sec'), ''}; ...
{'w_dot', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/sec^2'), ''}; ...
{'alpha', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'beta', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('rad'), ''}; ...
{'V_total', 1, 'double', 'real', 'Sample', 'Fixed', [], [], sprintf('ft/s'), ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
